export const constant = {
    subject: [
        { id: '0', name: 'Database Management System' },
        { id: '1', name: 'Object Oriented Programming' },
        { id: '2', name: 'Operating System' },
        // { id: '3', name: '' },
        // { id: '4', name: '' },
        // { id: '5', name: '' },
        // { id: '6', name: '' },
        // { id: '7', name: '' },
        // { id: '8', name: '' },
        // { id: '9', name: '' },
        // { id: '10', name: '' },
        // { id: '11', name: '' },
        // { id: '12', name: '' },
        // { id: '13', name: '' },
        // { id: '14', name: '' },
        // { id: '15', name: '' },
        // { id: '16', name: '' },
        // { id: '17', name: '' },
        // { id: '18', name: '' },
        // { id: '19', name: '' },
        // { id: '20', name: '' },
        // { id: '21', name: '' },
        // { id: '22', name: '' },
        // { id: '23', name: '' },
    ],
    department: [
        { id: '0', name: 'Computer Science & Engineering' },
        { id: '1', name: 'Electronics' },
        { id: '2', name: 'Mechanical' },
        { id: '3', name: 'Civil' },
        { id: '4', name: 'Artificial Intelligence & Data Science' },
    ],
    designation: [
        { id: '0', name: 'Administration' },
        { id: '1', name: 'College Faculty' },
        { id: '2', name: 'Alumini' },
        { id: '3', name: 'Student' },
    ]
   
}